[project]
name = "jennier0107.github.io"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "jennier0107", email = "mt3085570450@outlook.com"},
]
dependencies = []
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.scripts]
docs = {shell = "make html"}  # build sphinx docs
docs_export = { shell = "pdm export -G doc -o requirements.txt --without-hashes" }  # export requirements for docs
docs_preview = {shell = 'python -m http.server -d _build\html'}

[project.optional-dependencies]
doc = [
    "sphinx>=7.3.7",
    "sphinx-material>=0.0.36",
]
[tool.pdm]
distribution = false

